[package]
name = "blog_os"
version = "0.1.0"
authors = ["Mackenzie Clark <mackenzie.a.z.c@gmail.com>"]
edition = "2018"

[dependencies]
bootloader = "0.6.0"

#[profile.dev]
#panic = "abort"

#[profile.release]
#panic = "abort"
